using ConsumableComponents;
using ConsumableComponents.Consumables;

var player = new Player();
var apple = new Apple();
var applePie = new ApplePie();
var strengthPotion = new StrengthPotion();
var magicPotion = new MagicPotion();
var consumer = new ItemConsumer(player, apple);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, applePie);
consumer = new ItemConsumer(player, strengthPotion);
consumer = new ItemConsumer(player, strengthPotion);
consumer = new ItemConsumer(player, strengthPotion);
consumer = new ItemConsumer(player, magicPotion);
consumer = new ItemConsumer(player, magicPotion);
consumer = new ItemConsumer(player, magicPotion);
consumer = new ItemConsumer(player, magicPotion);
consumer = new ItemConsumer(player, magicPotion);
consumer = new ItemConsumer(player, magicPotion);
